### PR TITLE
Chinese translation for 1.12.2

### PR DESCRIPTION
**Pull request by rtxyd**
Hi, I made a Chinese translation. But I think the "herobrine_alter" may be "herobrine_altar".

### CODE REVIEW

**Comment by Alex-MacLean** [comment]
You are right about the herobrine_alter being the herobrine_altar. I will fix that typo in the next update.

**Comment by Alex-MacLean** [comment]
Do you want your name as "rtxyd" in the credits?

**Comment by rtxyd** [comment]
@Alex-MacLean As I am not a proffesional translator and the .lang file is short for now, I may not afford the best translation of further version. And I am glad to be one of it. But don't look forward to my CET-4 English.

**Comment by Alex-MacLean** [comment]
The translation seems complete to me. It covers all of the features added be the mod so far. Good luck on your CET-4 English.

**Comment by rtxyd** [comment]
The format of translation flie changed right? I hope I didn't pull a wrong format and make you fix my mistakes.

**Comment by Alex-MacLean** [comment]
Sorry for the late reply. You pulled the correct version. 1.12 is the version that uses the lang format. I did port the translation to 1.14/1.15 to the best of my abilities, but it may have some issues.

**Pull request merged**
